# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'E:\NMSU_Software_Projects\Relays_GUI\OPAL_RT_GUI_V2.ui'
#
# Created by: PyQt5 UI code generator 5.10
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1594, 794)
        MainWindow.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 200, 1131, 401))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.currentPhasor = currentPhasor(self.layoutWidget)
        self.currentPhasor.setObjectName("currentPhasor")
        self.horizontalLayout_2.addWidget(self.currentPhasor)
        self.voltagePhasor = voltagePhasor(self.layoutWidget)
        self.voltagePhasor.setObjectName("voltagePhasor")
        self.horizontalLayout_2.addWidget(self.voltagePhasor)
        self.xtraPlot = xtraPlot(self.layoutWidget)
        self.xtraPlot.setObjectName("xtraPlot")
        self.horizontalLayout_2.addWidget(self.xtraPlot)
        self.layoutWidget1 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget1.setGeometry(QtCore.QRect(11, 0, 1131, 191))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.current_Frame = QtWidgets.QFrame(self.layoutWidget1)
        self.current_Frame.setFrameShape(QtWidgets.QFrame.Box)
        self.current_Frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.current_Frame.setObjectName("current_Frame")
        self.layoutWidget2 = QtWidgets.QWidget(self.current_Frame)
        self.layoutWidget2.setGeometry(QtCore.QRect(10, 20, 261, 151))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.curr_table_layout = QtWidgets.QVBoxLayout(self.layoutWidget2)
        self.curr_table_layout.setContentsMargins(0, 0, 0, 0)
        self.curr_table_layout.setSpacing(7)
        self.curr_table_layout.setObjectName("curr_table_layout")
        self.Currents_per_phase_table_title = QtWidgets.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.Currents_per_phase_table_title.setFont(font)
        self.Currents_per_phase_table_title.setObjectName("Currents_per_phase_table_title")
        self.curr_table_layout.addWidget(self.Currents_per_phase_table_title)
        self.line = QtWidgets.QFrame(self.layoutWidget2)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.curr_table_layout.addWidget(self.line)
        self.Ia_horiz_layout = QtWidgets.QHBoxLayout()
        self.Ia_horiz_layout.setObjectName("Ia_horiz_layout")
        self.Ia = QtWidgets.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.Ia.setFont(font)
        self.Ia.setObjectName("Ia")
        self.Ia_horiz_layout.addWidget(self.Ia)
        self.mag_Ia = QtWidgets.QLabel(self.layoutWidget2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mag_Ia.sizePolicy().hasHeightForWidth())
        self.mag_Ia.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.mag_Ia.setFont(font)
        self.mag_Ia.setObjectName("mag_Ia")
        self.Ia_horiz_layout.addWidget(self.mag_Ia)
        self.angle_symbol_a = QtWidgets.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.angle_symbol_a.setFont(font)
        self.angle_symbol_a.setObjectName("angle_symbol_a")
        self.Ia_horiz_layout.addWidget(self.angle_symbol_a)
        self.deg_Ia = QtWidgets.QLabel(self.layoutWidget2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.deg_Ia.sizePolicy().hasHeightForWidth())
        self.deg_Ia.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.deg_Ia.setFont(font)
        self.deg_Ia.setObjectName("deg_Ia")
        self.Ia_horiz_layout.addWidget(self.deg_Ia)
        self.deg_symbol_Ia = QtWidgets.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.deg_symbol_Ia.setFont(font)
        self.deg_symbol_Ia.setObjectName("deg_symbol_Ia")
        self.Ia_horiz_layout.addWidget(self.deg_symbol_Ia)
        self.curr_table_layout.addLayout(self.Ia_horiz_layout)
        self.Ib_horiz_layout = QtWidgets.QHBoxLayout()
        self.Ib_horiz_layout.setObjectName("Ib_horiz_layout")
        self.Ib = QtWidgets.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.Ib.setFont(font)
        self.Ib.setObjectName("Ib")
        self.Ib_horiz_layout.addWidget(self.Ib)
        self.mag_Ib = QtWidgets.QLabel(self.layoutWidget2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mag_Ib.sizePolicy().hasHeightForWidth())
        self.mag_Ib.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.mag_Ib.setFont(font)
        self.mag_Ib.setObjectName("mag_Ib")
        self.Ib_horiz_layout.addWidget(self.mag_Ib)
        self.angle_symbol_b = QtWidgets.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.angle_symbol_b.setFont(font)
        self.angle_symbol_b.setObjectName("angle_symbol_b")
        self.Ib_horiz_layout.addWidget(self.angle_symbol_b)
        self.deg_Ib = QtWidgets.QLabel(self.layoutWidget2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.deg_Ib.sizePolicy().hasHeightForWidth())
        self.deg_Ib.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.deg_Ib.setFont(font)
        self.deg_Ib.setObjectName("deg_Ib")
        self.Ib_horiz_layout.addWidget(self.deg_Ib)
        self.deg_symbol_Ib = QtWidgets.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.deg_symbol_Ib.setFont(font)
        self.deg_symbol_Ib.setObjectName("deg_symbol_Ib")
        self.Ib_horiz_layout.addWidget(self.deg_symbol_Ib)
        self.curr_table_layout.addLayout(self.Ib_horiz_layout)
        self.Ic_horiz_layout = QtWidgets.QHBoxLayout()
        self.Ic_horiz_layout.setObjectName("Ic_horiz_layout")
        self.Ic = QtWidgets.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.Ic.setFont(font)
        self.Ic.setObjectName("Ic")
        self.Ic_horiz_layout.addWidget(self.Ic)
        self.mag_Ic = QtWidgets.QLabel(self.layoutWidget2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mag_Ic.sizePolicy().hasHeightForWidth())
        self.mag_Ic.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.mag_Ic.setFont(font)
        self.mag_Ic.setObjectName("mag_Ic")
        self.Ic_horiz_layout.addWidget(self.mag_Ic)
        self.angle_symbol_c = QtWidgets.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.angle_symbol_c.setFont(font)
        self.angle_symbol_c.setObjectName("angle_symbol_c")
        self.Ic_horiz_layout.addWidget(self.angle_symbol_c)
        self.deg_Ic = QtWidgets.QLabel(self.layoutWidget2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.deg_Ic.sizePolicy().hasHeightForWidth())
        self.deg_Ic.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.deg_Ic.setFont(font)
        self.deg_Ic.setObjectName("deg_Ic")
        self.Ic_horiz_layout.addWidget(self.deg_Ic)
        self.deg_symbol_Ic = QtWidgets.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.deg_symbol_Ic.setFont(font)
        self.deg_symbol_Ic.setObjectName("deg_symbol_Ic")
        self.Ic_horiz_layout.addWidget(self.deg_symbol_Ic)
        self.curr_table_layout.addLayout(self.Ic_horiz_layout)
        self.horizontalLayout.addWidget(self.current_Frame)
        self.voltage_Frame = QtWidgets.QFrame(self.layoutWidget1)
        self.voltage_Frame.setFrameShape(QtWidgets.QFrame.Box)
        self.voltage_Frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.voltage_Frame.setObjectName("voltage_Frame")
        self.layoutWidget3 = QtWidgets.QWidget(self.voltage_Frame)
        self.layoutWidget3.setGeometry(QtCore.QRect(10, 20, 261, 151))
        self.layoutWidget3.setObjectName("layoutWidget3")
        self.volt_table_layout = QtWidgets.QVBoxLayout(self.layoutWidget3)
        self.volt_table_layout.setContentsMargins(0, 0, 0, 0)
        self.volt_table_layout.setObjectName("volt_table_layout")
        self.voltages_per_phase_table_title = QtWidgets.QLabel(self.layoutWidget3)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.voltages_per_phase_table_title.setFont(font)
        self.voltages_per_phase_table_title.setObjectName("voltages_per_phase_table_title")
        self.volt_table_layout.addWidget(self.voltages_per_phase_table_title)
        self.line_2 = QtWidgets.QFrame(self.layoutWidget3)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.volt_table_layout.addWidget(self.line_2)
        self.va_horiz_layout = QtWidgets.QHBoxLayout()
        self.va_horiz_layout.setObjectName("va_horiz_layout")
        self.Va = QtWidgets.QLabel(self.layoutWidget3)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.Va.setFont(font)
        self.Va.setObjectName("Va")
        self.va_horiz_layout.addWidget(self.Va)
        self.mag_Va = QtWidgets.QLabel(self.layoutWidget3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mag_Va.sizePolicy().hasHeightForWidth())
        self.mag_Va.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.mag_Va.setFont(font)
        self.mag_Va.setObjectName("mag_Va")
        self.va_horiz_layout.addWidget(self.mag_Va)
        self.angle_sym_Va = QtWidgets.QLabel(self.layoutWidget3)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.angle_sym_Va.setFont(font)
        self.angle_sym_Va.setObjectName("angle_sym_Va")
        self.va_horiz_layout.addWidget(self.angle_sym_Va)
        self.deg_Va = QtWidgets.QLabel(self.layoutWidget3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.deg_Va.sizePolicy().hasHeightForWidth())
        self.deg_Va.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.deg_Va.setFont(font)
        self.deg_Va.setObjectName("deg_Va")
        self.va_horiz_layout.addWidget(self.deg_Va)
        self.deg_sym_Va = QtWidgets.QLabel(self.layoutWidget3)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.deg_sym_Va.setFont(font)
        self.deg_sym_Va.setObjectName("deg_sym_Va")
        self.va_horiz_layout.addWidget(self.deg_sym_Va)
        self.volt_table_layout.addLayout(self.va_horiz_layout)
        self.vb_horiz_layout = QtWidgets.QHBoxLayout()
        self.vb_horiz_layout.setObjectName("vb_horiz_layout")
        self.Vb = QtWidgets.QLabel(self.layoutWidget3)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.Vb.setFont(font)
        self.Vb.setObjectName("Vb")
        self.vb_horiz_layout.addWidget(self.Vb)
        self.mag_Vb = QtWidgets.QLabel(self.layoutWidget3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mag_Vb.sizePolicy().hasHeightForWidth())
        self.mag_Vb.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.mag_Vb.setFont(font)
        self.mag_Vb.setObjectName("mag_Vb")
        self.vb_horiz_layout.addWidget(self.mag_Vb)
        self.angle_sym_Vb = QtWidgets.QLabel(self.layoutWidget3)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.angle_sym_Vb.setFont(font)
        self.angle_sym_Vb.setObjectName("angle_sym_Vb")
        self.vb_horiz_layout.addWidget(self.angle_sym_Vb)
        self.deg_Vb = QtWidgets.QLabel(self.layoutWidget3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.deg_Vb.sizePolicy().hasHeightForWidth())
        self.deg_Vb.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.deg_Vb.setFont(font)
        self.deg_Vb.setObjectName("deg_Vb")
        self.vb_horiz_layout.addWidget(self.deg_Vb)
        self.deg_sym_Vb = QtWidgets.QLabel(self.layoutWidget3)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.deg_sym_Vb.setFont(font)
        self.deg_sym_Vb.setObjectName("deg_sym_Vb")
        self.vb_horiz_layout.addWidget(self.deg_sym_Vb)
        self.volt_table_layout.addLayout(self.vb_horiz_layout)
        self.vc_horiz_layout = QtWidgets.QHBoxLayout()
        self.vc_horiz_layout.setObjectName("vc_horiz_layout")
        self.Vc = QtWidgets.QLabel(self.layoutWidget3)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.Vc.setFont(font)
        self.Vc.setObjectName("Vc")
        self.vc_horiz_layout.addWidget(self.Vc)
        self.mag_Vc = QtWidgets.QLabel(self.layoutWidget3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mag_Vc.sizePolicy().hasHeightForWidth())
        self.mag_Vc.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.mag_Vc.setFont(font)
        self.mag_Vc.setObjectName("mag_Vc")
        self.vc_horiz_layout.addWidget(self.mag_Vc)
        self.angle_sym_Vc = QtWidgets.QLabel(self.layoutWidget3)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.angle_sym_Vc.setFont(font)
        self.angle_sym_Vc.setObjectName("angle_sym_Vc")
        self.vc_horiz_layout.addWidget(self.angle_sym_Vc)
        self.deg_Vc = QtWidgets.QLabel(self.layoutWidget3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.deg_Vc.sizePolicy().hasHeightForWidth())
        self.deg_Vc.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.deg_Vc.setFont(font)
        self.deg_Vc.setObjectName("deg_Vc")
        self.vc_horiz_layout.addWidget(self.deg_Vc)
        self.deg_sym_Vc = QtWidgets.QLabel(self.layoutWidget3)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.deg_sym_Vc.setFont(font)
        self.deg_sym_Vc.setObjectName("deg_sym_Vc")
        self.vc_horiz_layout.addWidget(self.deg_sym_Vc)
        self.volt_table_layout.addLayout(self.vc_horiz_layout)
        self.horizontalLayout.addWidget(self.voltage_Frame)
        self.power_Frame = QtWidgets.QFrame(self.layoutWidget1)
        self.power_Frame.setFrameShape(QtWidgets.QFrame.Box)
        self.power_Frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.power_Frame.setObjectName("power_Frame")
        self.layoutWidget_2 = QtWidgets.QWidget(self.power_Frame)
        self.layoutWidget_2.setGeometry(QtCore.QRect(10, 20, 261, 151))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.volt_table_layout_2 = QtWidgets.QVBoxLayout(self.layoutWidget_2)
        self.volt_table_layout_2.setContentsMargins(0, 0, 0, 0)
        self.volt_table_layout_2.setObjectName("volt_table_layout_2")
        self.power_per_phase_table_title = QtWidgets.QLabel(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.power_per_phase_table_title.setFont(font)
        self.power_per_phase_table_title.setObjectName("power_per_phase_table_title")
        self.volt_table_layout_2.addWidget(self.power_per_phase_table_title)
        self.line_3 = QtWidgets.QFrame(self.layoutWidget_2)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.volt_table_layout_2.addWidget(self.line_3)
        self.va_horiz_layout_2 = QtWidgets.QHBoxLayout()
        self.va_horiz_layout_2.setObjectName("va_horiz_layout_2")
        self.Pa = QtWidgets.QLabel(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.Pa.setFont(font)
        self.Pa.setObjectName("Pa")
        self.va_horiz_layout_2.addWidget(self.Pa)
        self.mag_Pa = QtWidgets.QLabel(self.layoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mag_Pa.sizePolicy().hasHeightForWidth())
        self.mag_Pa.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.mag_Pa.setFont(font)
        self.mag_Pa.setObjectName("mag_Pa")
        self.va_horiz_layout_2.addWidget(self.mag_Pa)
        self.angle_sym_Pa = QtWidgets.QLabel(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.angle_sym_Pa.setFont(font)
        self.angle_sym_Pa.setObjectName("angle_sym_Pa")
        self.va_horiz_layout_2.addWidget(self.angle_sym_Pa)
        self.deg_Pa = QtWidgets.QLabel(self.layoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.deg_Pa.sizePolicy().hasHeightForWidth())
        self.deg_Pa.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.deg_Pa.setFont(font)
        self.deg_Pa.setObjectName("deg_Pa")
        self.va_horiz_layout_2.addWidget(self.deg_Pa)
        self.deg_sym_Pa = QtWidgets.QLabel(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.deg_sym_Pa.setFont(font)
        self.deg_sym_Pa.setObjectName("deg_sym_Pa")
        self.va_horiz_layout_2.addWidget(self.deg_sym_Pa)
        self.volt_table_layout_2.addLayout(self.va_horiz_layout_2)
        self.vb_horiz_layout_2 = QtWidgets.QHBoxLayout()
        self.vb_horiz_layout_2.setObjectName("vb_horiz_layout_2")
        self.Pb = QtWidgets.QLabel(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.Pb.setFont(font)
        self.Pb.setObjectName("Pb")
        self.vb_horiz_layout_2.addWidget(self.Pb)
        self.mag_Pb = QtWidgets.QLabel(self.layoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mag_Pb.sizePolicy().hasHeightForWidth())
        self.mag_Pb.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.mag_Pb.setFont(font)
        self.mag_Pb.setObjectName("mag_Pb")
        self.vb_horiz_layout_2.addWidget(self.mag_Pb)
        self.angle_sym_Pb = QtWidgets.QLabel(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.angle_sym_Pb.setFont(font)
        self.angle_sym_Pb.setObjectName("angle_sym_Pb")
        self.vb_horiz_layout_2.addWidget(self.angle_sym_Pb)
        self.deg_Pb = QtWidgets.QLabel(self.layoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.deg_Pb.sizePolicy().hasHeightForWidth())
        self.deg_Pb.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.deg_Pb.setFont(font)
        self.deg_Pb.setObjectName("deg_Pb")
        self.vb_horiz_layout_2.addWidget(self.deg_Pb)
        self.deg_sym_Pb = QtWidgets.QLabel(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.deg_sym_Pb.setFont(font)
        self.deg_sym_Pb.setObjectName("deg_sym_Pb")
        self.vb_horiz_layout_2.addWidget(self.deg_sym_Pb)
        self.volt_table_layout_2.addLayout(self.vb_horiz_layout_2)
        self.vc_horiz_layout_2 = QtWidgets.QHBoxLayout()
        self.vc_horiz_layout_2.setObjectName("vc_horiz_layout_2")
        self.Pc = QtWidgets.QLabel(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.Pc.setFont(font)
        self.Pc.setObjectName("Pc")
        self.vc_horiz_layout_2.addWidget(self.Pc)
        self.mag_Pc = QtWidgets.QLabel(self.layoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mag_Pc.sizePolicy().hasHeightForWidth())
        self.mag_Pc.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.mag_Pc.setFont(font)
        self.mag_Pc.setObjectName("mag_Pc")
        self.vc_horiz_layout_2.addWidget(self.mag_Pc)
        self.angle_sym_Pc = QtWidgets.QLabel(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.angle_sym_Pc.setFont(font)
        self.angle_sym_Pc.setObjectName("angle_sym_Pc")
        self.vc_horiz_layout_2.addWidget(self.angle_sym_Pc)
        self.deg_Pc = QtWidgets.QLabel(self.layoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.deg_Pc.sizePolicy().hasHeightForWidth())
        self.deg_Pc.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.deg_Pc.setFont(font)
        self.deg_Pc.setObjectName("deg_Pc")
        self.vc_horiz_layout_2.addWidget(self.deg_Pc)
        self.deg_sym_Pc = QtWidgets.QLabel(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.deg_sym_Pc.setFont(font)
        self.deg_sym_Pc.setObjectName("deg_sym_Pc")
        self.vc_horiz_layout_2.addWidget(self.deg_sym_Pc)
        self.volt_table_layout_2.addLayout(self.vc_horiz_layout_2)
        self.horizontalLayout.addWidget(self.power_Frame)
        self.power_Frame_2 = QtWidgets.QFrame(self.layoutWidget1)
        self.power_Frame_2.setFrameShape(QtWidgets.QFrame.Box)
        self.power_Frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.power_Frame_2.setObjectName("power_Frame_2")
        self.layoutWidget_3 = QtWidgets.QWidget(self.power_Frame_2)
        self.layoutWidget_3.setGeometry(QtCore.QRect(10, 20, 271, 151))
        self.layoutWidget_3.setObjectName("layoutWidget_3")
        self.volt_table_layout_3 = QtWidgets.QVBoxLayout(self.layoutWidget_3)
        self.volt_table_layout_3.setContentsMargins(0, 0, 0, 0)
        self.volt_table_layout_3.setObjectName("volt_table_layout_3")
        self.impedance_per_phase_table_title_ = QtWidgets.QLabel(self.layoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.impedance_per_phase_table_title_.setFont(font)
        self.impedance_per_phase_table_title_.setObjectName("impedance_per_phase_table_title_")
        self.volt_table_layout_3.addWidget(self.impedance_per_phase_table_title_)
        self.line_4 = QtWidgets.QFrame(self.layoutWidget_3)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.volt_table_layout_3.addWidget(self.line_4)
        self.va_horiz_layout_3 = QtWidgets.QHBoxLayout()
        self.va_horiz_layout_3.setObjectName("va_horiz_layout_3")
        self.Za = QtWidgets.QLabel(self.layoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.Za.setFont(font)
        self.Za.setObjectName("Za")
        self.va_horiz_layout_3.addWidget(self.Za)
        self.mag_Za = QtWidgets.QLabel(self.layoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mag_Za.sizePolicy().hasHeightForWidth())
        self.mag_Za.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.mag_Za.setFont(font)
        self.mag_Za.setObjectName("mag_Za")
        self.va_horiz_layout_3.addWidget(self.mag_Za)
        self.angle_sym_Za = QtWidgets.QLabel(self.layoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.angle_sym_Za.setFont(font)
        self.angle_sym_Za.setObjectName("angle_sym_Za")
        self.va_horiz_layout_3.addWidget(self.angle_sym_Za)
        self.deg_Za = QtWidgets.QLabel(self.layoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.deg_Za.sizePolicy().hasHeightForWidth())
        self.deg_Za.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.deg_Za.setFont(font)
        self.deg_Za.setObjectName("deg_Za")
        self.va_horiz_layout_3.addWidget(self.deg_Za)
        self.deg_sym_Za = QtWidgets.QLabel(self.layoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.deg_sym_Za.setFont(font)
        self.deg_sym_Za.setObjectName("deg_sym_Za")
        self.va_horiz_layout_3.addWidget(self.deg_sym_Za)
        self.volt_table_layout_3.addLayout(self.va_horiz_layout_3)
        self.vb_horiz_layout_3 = QtWidgets.QHBoxLayout()
        self.vb_horiz_layout_3.setObjectName("vb_horiz_layout_3")
        self.Zb = QtWidgets.QLabel(self.layoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.Zb.setFont(font)
        self.Zb.setObjectName("Zb")
        self.vb_horiz_layout_3.addWidget(self.Zb)
        self.mag_Zb = QtWidgets.QLabel(self.layoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mag_Zb.sizePolicy().hasHeightForWidth())
        self.mag_Zb.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.mag_Zb.setFont(font)
        self.mag_Zb.setObjectName("mag_Zb")
        self.vb_horiz_layout_3.addWidget(self.mag_Zb)
        self.angle_sym_Zb = QtWidgets.QLabel(self.layoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.angle_sym_Zb.setFont(font)
        self.angle_sym_Zb.setObjectName("angle_sym_Zb")
        self.vb_horiz_layout_3.addWidget(self.angle_sym_Zb)
        self.deg_Zb = QtWidgets.QLabel(self.layoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.deg_Zb.sizePolicy().hasHeightForWidth())
        self.deg_Zb.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.deg_Zb.setFont(font)
        self.deg_Zb.setObjectName("deg_Zb")
        self.vb_horiz_layout_3.addWidget(self.deg_Zb)
        self.deg_sym_Zb = QtWidgets.QLabel(self.layoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.deg_sym_Zb.setFont(font)
        self.deg_sym_Zb.setObjectName("deg_sym_Zb")
        self.vb_horiz_layout_3.addWidget(self.deg_sym_Zb)
        self.volt_table_layout_3.addLayout(self.vb_horiz_layout_3)
        self.vc_horiz_layout_3 = QtWidgets.QHBoxLayout()
        self.vc_horiz_layout_3.setObjectName("vc_horiz_layout_3")
        self.Zc = QtWidgets.QLabel(self.layoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.Zc.setFont(font)
        self.Zc.setObjectName("Zc")
        self.vc_horiz_layout_3.addWidget(self.Zc)
        self.mag_Zc = QtWidgets.QLabel(self.layoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mag_Zc.sizePolicy().hasHeightForWidth())
        self.mag_Zc.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.mag_Zc.setFont(font)
        self.mag_Zc.setObjectName("mag_Zc")
        self.vc_horiz_layout_3.addWidget(self.mag_Zc)
        self.angle_sym_Zc = QtWidgets.QLabel(self.layoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.angle_sym_Zc.setFont(font)
        self.angle_sym_Zc.setObjectName("angle_sym_Zc")
        self.vc_horiz_layout_3.addWidget(self.angle_sym_Zc)
        self.deg_Zc = QtWidgets.QLabel(self.layoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.deg_Zc.sizePolicy().hasHeightForWidth())
        self.deg_Zc.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.deg_Zc.setFont(font)
        self.deg_Zc.setObjectName("deg_Zc")
        self.vc_horiz_layout_3.addWidget(self.deg_Zc)
        self.deg_sym_Zc = QtWidgets.QLabel(self.layoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.deg_sym_Zc.setFont(font)
        self.deg_sym_Zc.setObjectName("deg_sym_Zc")
        self.vc_horiz_layout_3.addWidget(self.deg_sym_Zc)
        self.volt_table_layout_3.addLayout(self.vc_horiz_layout_3)
        self.horizontalLayout.addWidget(self.power_Frame_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1594, 26))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuAnalysis = QtWidgets.QMenu(self.menubar)
        self.menuAnalysis.setObjectName("menuAnalysis")
        self.menuAdministrator = QtWidgets.QMenu(self.menubar)
        self.menuAdministrator.setObjectName("menuAdministrator")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionExport_Values_CSV = QtWidgets.QAction(MainWindow)
        self.actionExport_Values_CSV.setObjectName("actionExport_Values_CSV")
        self.actionPlots = QtWidgets.QAction(MainWindow)
        self.actionPlots.setObjectName("actionPlots")
        self.actionLogin = QtWidgets.QAction(MainWindow)
        self.actionLogin.setObjectName("actionLogin")
        self.menuFile.addAction(self.actionExport_Values_CSV)
        self.menuAnalysis.addAction(self.actionPlots)
        self.menuAdministrator.addAction(self.actionLogin)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuAnalysis.menuAction())
        self.menubar.addAction(self.menuAdministrator.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Currents_per_phase_table_title.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">Current</p></body></html>"))
        self.Ia.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">I</span><span style=\" font-weight:600; vertical-align:sub;\">A </span><span style=\" font-weight:600;\">=</span></p></body></html>"))
        self.mag_Ia.setText(_translate("MainWindow", "Magn "))
        self.angle_symbol_a.setText(_translate("MainWindow", "∠"))
        self.deg_Ia.setText(_translate("MainWindow", "degree "))
        self.deg_symbol_Ia.setText(_translate("MainWindow", "°"))
        self.Ib.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">I</span><span style=\" font-weight:600; vertical-align:sub;\">B </span><span style=\" font-weight:600;\">=</span></p></body></html>"))
        self.mag_Ib.setText(_translate("MainWindow", "Magn "))
        self.angle_symbol_b.setText(_translate("MainWindow", "∠"))
        self.deg_Ib.setText(_translate("MainWindow", "degree "))
        self.deg_symbol_Ib.setText(_translate("MainWindow", "°"))
        self.Ic.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">I</span><span style=\" font-weight:600; vertical-align:sub;\">C </span><span style=\" font-weight:600;\">=</span></p></body></html>"))
        self.mag_Ic.setText(_translate("MainWindow", "Magn "))
        self.angle_symbol_c.setText(_translate("MainWindow", "∠"))
        self.deg_Ic.setText(_translate("MainWindow", "degree "))
        self.deg_symbol_Ic.setText(_translate("MainWindow", "°"))
        self.voltages_per_phase_table_title.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">Voltage</p></body></html>"))
        self.Va.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">V</span><span style=\" font-weight:600; vertical-align:sub;\">A </span><span style=\" font-weight:600;\">=</span></p></body></html>"))
        self.mag_Va.setText(_translate("MainWindow", "Magn "))
        self.angle_sym_Va.setText(_translate("MainWindow", "∠"))
        self.deg_Va.setText(_translate("MainWindow", "degree "))
        self.deg_sym_Va.setText(_translate("MainWindow", "°"))
        self.Vb.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">V</span><span style=\" font-weight:600; vertical-align:sub;\">B </span><span style=\" font-weight:600;\">=</span></p></body></html>"))
        self.mag_Vb.setText(_translate("MainWindow", "Magn "))
        self.angle_sym_Vb.setText(_translate("MainWindow", "∠"))
        self.deg_Vb.setText(_translate("MainWindow", "degree "))
        self.deg_sym_Vb.setText(_translate("MainWindow", "°"))
        self.Vc.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">V</span><span style=\" font-weight:600; vertical-align:sub;\">C </span><span style=\" font-weight:600;\">=</span></p></body></html>"))
        self.mag_Vc.setText(_translate("MainWindow", "Magn "))
        self.angle_sym_Vc.setText(_translate("MainWindow", "∠"))
        self.deg_Vc.setText(_translate("MainWindow", "degree "))
        self.deg_sym_Vc.setText(_translate("MainWindow", "°"))
        self.power_per_phase_table_title.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">Power</p></body></html>"))
        self.Pa.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">P</span><span style=\" font-weight:600; vertical-align:sub;\">A </span><span style=\" font-weight:600;\">=</span></p></body></html>"))
        self.mag_Pa.setText(_translate("MainWindow", "Magn "))
        self.angle_sym_Pa.setText(_translate("MainWindow", "∠"))
        self.deg_Pa.setText(_translate("MainWindow", "degree "))
        self.deg_sym_Pa.setText(_translate("MainWindow", "°"))
        self.Pb.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">P</span><span style=\" font-weight:600; vertical-align:sub;\">B </span><span style=\" font-weight:600;\">=</span></p></body></html>"))
        self.mag_Pb.setText(_translate("MainWindow", "Magn "))
        self.angle_sym_Pb.setText(_translate("MainWindow", "∠"))
        self.deg_Pb.setText(_translate("MainWindow", "degree "))
        self.deg_sym_Pb.setText(_translate("MainWindow", "°"))
        self.Pc.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">P</span><span style=\" font-weight:600; vertical-align:sub;\">C </span><span style=\" font-weight:600;\">=</span></p></body></html>"))
        self.mag_Pc.setText(_translate("MainWindow", "Magn "))
        self.angle_sym_Pc.setText(_translate("MainWindow", "∠"))
        self.deg_Pc.setText(_translate("MainWindow", "degree "))
        self.deg_sym_Pc.setText(_translate("MainWindow", "°"))
        self.impedance_per_phase_table_title_.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">Impedance</p></body></html>"))
        self.Za.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Z</span><span style=\" font-weight:600; vertical-align:sub;\">A </span><span style=\" font-weight:600;\">=</span></p></body></html>"))
        self.mag_Za.setText(_translate("MainWindow", "Magn "))
        self.angle_sym_Za.setText(_translate("MainWindow", "∠"))
        self.deg_Za.setText(_translate("MainWindow", "degree "))
        self.deg_sym_Za.setText(_translate("MainWindow", "°"))
        self.Zb.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Z</span><span style=\" font-weight:600; vertical-align:sub;\">B </span><span style=\" font-weight:600;\">=</span></p></body></html>"))
        self.mag_Zb.setText(_translate("MainWindow", "Magn "))
        self.angle_sym_Zb.setText(_translate("MainWindow", "∠"))
        self.deg_Zb.setText(_translate("MainWindow", "degree "))
        self.deg_sym_Zb.setText(_translate("MainWindow", "°"))
        self.Zc.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Z</span><span style=\" font-weight:600; vertical-align:sub;\">C </span><span style=\" font-weight:600;\">=</span></p></body></html>"))
        self.mag_Zc.setText(_translate("MainWindow", "Magn "))
        self.angle_sym_Zc.setText(_translate("MainWindow", "∠"))
        self.deg_Zc.setText(_translate("MainWindow", "degree "))
        self.deg_sym_Zc.setText(_translate("MainWindow", "°"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuAnalysis.setTitle(_translate("MainWindow", "Analysis"))
        self.menuAdministrator.setTitle(_translate("MainWindow", "Administrator"))
        self.actionExport_Values_CSV.setText(_translate("MainWindow", "Export Values (*.CSV)"))
        self.actionPlots.setText(_translate("MainWindow", "Faults"))
        self.actionLogin.setText(_translate("MainWindow", "Login"))

from currentphasor import currentPhasor
from voltagephasor import voltagePhasor
from xtraplot import xtraPlot
